version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: product_ideas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-node:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    container_name: backend-node
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/product_ideas?schema=public
    depends_on:
      - postgres
    volumes:
      - ./backend-node:/app
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run test &&
        npm run dev
      "
    

  backend-php:
    build: ./backend-php
    dockerfile: Dockerfile
    container_name: backend-php
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=product_ideas
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
    depends_on:
      - postgres
    volumes:
      - ./backend-laravel-mvc:/var/www/html
    command: >
      sh -c "
        php artisan migrate --force &&
        php artisan db:seed --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE: http://localhost:4000
    ports:
      - "5173:5173"
    depends_on:
      - backend-node

volumes:
  postgres_data:
